apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: echo-operator
  template:
    metadata:
      labels:
        name: echo-operator
    spec:
      containers:
        - name: echo-operator
          image: docker.io/tohinkashem/echo-operator:v0.0.1
          command:
          - echo-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
